// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhtfcupsnfmidligzjmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRodGZjdXBzbmZtaWRsaWd6am1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjEyODAsImV4cCI6MjA2MTIzNzI4MH0.o1t7sjTYxl4jzpO1cyZHr0lqYr3KkfrlAUa4byv1oLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);